# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NsITNJ82SqcQF-J85Hv-jCtvI2q6JFHc
"""

from .bisec_py import biseccion
from .metnewton_py import newton
from .puntof_py import itera
from .secante import secante
from .secv2_py import secante2

__all__= ['biseccion', 'newton', 'itera', 'secante', 'secante2']