# -*- coding: utf-8 -*-
"""__init__

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DZ2bMeOokETbr_OhUJ_BKOHjvJVl7jmt
"""

from .MetodosRaices.metodos_num import biseccion
from .MetodosRaices.metodos_num import newton
from .MetodosRaices.metodos_num import itera
from .MetodosRaices.metodos_num import secante
from .MetodosRaices.metodos_num import secante2

__all__= ['biseccion', 'newton', 'itera', 'secante', 'secante2']